version: '3.5'

services:
  backend:
    build: backend-example-docker/.
    volumes:
      - ./backend-example-docker/logs.txt:/workdir/logs.txt
    container_name: backend
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=SuperSecret
      - DB_NAME=postgres
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    volumes:
      - ./data:/data
    container_name: redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=SuperSecret
  
  frontend:
    build: ./frontend-example-docker/.
    container_name: frontend

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
